#!/bin/bash
isWorkDirClean(){
    if [ -z "$(git status --porcelain)" ]; then
        return 0
    fi
    return 1
}

test_command="$@"

if ! isWorkDirClean; then
    $test_command && git commit -am "WIP" || git reset --hard
fi
