name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run:
    - name: Run a multi-line script
      run: |
        export PATH="/home/runner/.cask/bin:$PATH" && make install && make test
