name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install and test
      run: |
        export PATH="/home/runner/.cask/bin:$PATH" && bash install_CI.sh && bash test_CI.sh
